### ISSUE TITLE
Reading HDF5 files appropriately

### ISSUE THREAD

**Issue by ShaileshSridhar2403** [flyer2403/Sounds-Like-Data#4]
The dataset is saved in HDF5 file format. It can not be easily converted into  CSV format as several fields in the dataset are arrays and not single values.

A good way to read these files and represent them so that necessary operations can be carried out on them must be found.

**Comment by shashank-prabhakar** [comment]
[Reading_H5_Attributes.zip](https://github.com/flyer2403/Sounds-Like-Data/files/2475754/Reading_H5_Attributes.zip)

The Million Song Dataset website provides a link to a repo containing a python script to extract attributes from the H5 files. The ipynb file in the zip file attached has extracted the titles of the songs. The same can be used to extract al the attributes specified on the website. Once we have arrays of all attributes, we can combine them to form a DataFrame, which can converted to a csv file if needed.
